//! Cross-language differential: the Rust move generator must produce exactly
//! the same legal-move set as the already-validated `smallboard` Python engine
//! on square boards. The fixture is generated by
//! `scripts/gen_solver_fixture.py`; regenerate it whenever the rules change.

use quoridor_solver::board::Board;
use quoridor_solver::movegen::legal_moves;
use quoridor_solver::state::{Move, State};
use serde_json::Value;

/// Encode a Rust `Move` into the same key string the Python fixture uses:
///   step to cell (c, r) -> "S c r"
///   horizontal wall     -> "H wc wr"
///   vertical wall        -> "V wc wr"
fn move_key(b: &Board, m: &Move) -> String {
    match *m {
        Move::Step(dest) => {
            let (c, r) = b.cr(dest);
            format!("S {c} {r}")
        }
        Move::Wall { wc, wr, horiz } => {
            let o = if horiz { 'H' } else { 'V' };
            format!("{o} {wc} {wr}")
        }
    }
}

#[test]
fn legal_moves_match_smallboard() {
    let raw = include_str!("fixtures/smallboard_diff.json");
    let records: Vec<Value> = serde_json::from_str(raw).expect("fixture parses");

    let mut checked = 0usize;
    for (i, rec) in records.iter().enumerate() {
        let w = rec["w"].as_u64().unwrap() as u8;
        let h = rec["h"].as_u64().unwrap() as u8;
        let walls = rec["walls"].as_u64().unwrap() as u8;
        let b = Board::new(w, h, walls);

        // Reconstruct the position.
        let pawns = rec["pawns"].as_array().unwrap();
        let pawn0 = pawns[0].as_array().unwrap();
        let pawn1 = pawns[1].as_array().unwrap();
        let p0 = b.idx(pawn0[0].as_u64().unwrap() as u8, pawn0[1].as_u64().unwrap() as u8);
        let p1 = b.idx(pawn1[0].as_u64().unwrap() as u8, pawn1[1].as_u64().unwrap() as u8);

        let mut h_walls = 0u64;
        for wall in rec["h_walls"].as_array().unwrap() {
            let wall = wall.as_array().unwrap();
            let (wc, wr) = (wall[0].as_u64().unwrap() as u8, wall[1].as_u64().unwrap() as u8);
            h_walls |= 1u64 << b.hbit(wc, wr);
        }
        let mut v_walls = 0u64;
        for wall in rec["v_walls"].as_array().unwrap() {
            let wall = wall.as_array().unwrap();
            let (wc, wr) = (wall[0].as_u64().unwrap() as u8, wall[1].as_u64().unwrap() as u8);
            v_walls |= 1u64 << b.vbit(wc, wr);
        }

        let wl = rec["walls_left"].as_array().unwrap();
        let walls_left = [wl[0].as_u64().unwrap() as u8, wl[1].as_u64().unwrap() as u8];
        let turn = rec["turn"].as_u64().unwrap() as u8;

        let s = State { pawn: [p0, p1], h_walls, v_walls, walls_left, turn };

        // Compute our legal moves, encode, sort.
        let mut got: Vec<String> = legal_moves(&b, &s).iter().map(|m| move_key(&b, m)).collect();
        got.sort();

        let want: Vec<String> = rec["moves"]
            .as_array()
            .unwrap()
            .iter()
            .map(|m| m.as_str().unwrap().to_string())
            .collect();
        // The fixture's `moves` are already sorted, but sort defensively.
        let mut want = want;
        want.sort();

        assert_eq!(
            got, want,
            "record #{i} mismatch (w={w},h={h},turn={turn},pawns={:?})",
            s.pawn
        );
        checked += 1;
    }

    assert!(checked >= 800, "only {checked} records checked, need >= 800");
}
